const express=require("express");
const session=require("express-session");
const multer=require("multer");
const path=require("path");
const fs=require("fs");
const app=express(), PORT=process.env.PORT||3000, ROOT=__dirname;
const UPLOAD_DIR=path.join(ROOT,"uploads"), DATA_FILE=path.join(ROOT,"data.json");
fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const DEFAULT={admins:[{id:1,username:"admin",password:"admin123"}],photos:[],notices:[],settings:{phone:"9849343124",email:"bethanchok.narisaccos@gmail.com"}};
function load(){try{return JSON.parse(fs.readFileSync(DATA_FILE,"utf8"))}catch{fs.writeFileSync(DATA_FILE,JSON.stringify(DEFAULT,null,2));return JSON.parse(JSON.stringify(DEFAULT))}}
let db=load(); const save=()=>fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2));
const next=a=>a.length?Math.max(...a.map(x=>+x.id||0))+1:1;
app.use(express.json({limit:"2mb"})); app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||"CHANGE_THIS_SECRET",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:false,maxAge:28800000}}));
app.use(express.static(ROOT)); app.use("/uploads",express.static(UPLOAD_DIR));
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,UPLOAD_DIR),filename:(_,f,cb)=>cb(null,Date.now()+"-"+Math.random().toString(36).slice(2,9)+path.extname(f.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(_,f,cb)=>{const ok=[".jpg",".jpeg",".png",".webp",".gif"].includes(path.extname(f.originalname).toLowerCase());cb(ok?null:new Error("Only image files are allowed"),ok)}});
const auth=(req,res,next)=>req.session.admin?next():res.status(401).json({error:"Unauthorized"});
app.post("/api/admin/login",(req,res)=>{const a=db.admins.find(x=>x.username===req.body.username&&x.password===req.body.password);if(!a)return res.status(401).json({error:"Invalid username or password"});req.session.admin={id:a.id,username:a.username};res.json({ok:true,username:a.username})});
app.post("/api/admin/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/admin/me",(req,res)=>res.json({loggedIn:!!req.session.admin,user:req.session.admin||null}));
app.post("/api/photos",auth,upload.single("photo"),(req,res)=>{if(!req.file)return res.status(400).json({error:"Photo is required"});const r={id:next(db.photos),category:req.body.category||"gallery",person_key:req.body.personKey||null,title:req.body.title||null,filename:req.file.filename,created_at:new Date().toISOString()};db.photos.push(r);save();res.json({ok:true,id:r.id,url:"/uploads/"+r.filename})});
app.get("/api/photos",(req,res)=>{let a=db.photos;if(req.query.category)a=a.filter(x=>x.category===req.query.category);res.json(a.slice().reverse().map(x=>({...x,url:"/uploads/"+x.filename})))});
app.delete("/api/photos/:id",auth,(req,res)=>{const i=db.photos.findIndex(x=>x.id===+req.params.id);if(i<0)return res.status(404).json({error:"Not found"});try{fs.unlinkSync(path.join(UPLOAD_DIR,db.photos[i].filename))}catch{}db.photos.splice(i,1);save();res.json({ok:true})});
app.get("/api/notices",(req,res)=>res.json(db.notices.slice().reverse()));
app.post("/api/notices",auth,(req,res)=>{if(!req.body.title||!req.body.body)return res.status(400).json({error:"Title and body are required"});const r={id:next(db.notices),title:req.body.title,body:req.body.body,created_at:new Date().toISOString()};db.notices.push(r);save();res.json(r)});
app.delete("/api/notices/:id",auth,(req,res)=>{db.notices=db.notices.filter(x=>x.id!==+req.params.id);save();res.json({ok:true})});
app.get("/api/settings",(req,res)=>res.json(db.settings));
app.put("/api/settings",auth,(req,res)=>{Object.assign(db.settings,req.body||{});save();res.json({ok:true})});
app.get("/api/health",(req,res)=>res.json({ok:true}));
app.use((err,req,res,next)=>res.status(400).json({error:err.message||"Request failed"}));
app.listen(PORT,()=>console.log("Website running at http://localhost:"+PORT));
